[package]
name = "make_singleton_test"
version = "0.1.0"
authors = ["yangshubo <yangshubo@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
make_singleton = { path= "../"}
